import Head from "next/head";

import Layout from "components/layout";
import styled from "styled-components";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tmp>` hello by `</Tmp>
    </>
  );
};

export default Home;
Home.Layout = Layout;

const Tmp = styled.pre`
  margin: 0;
  background-color: white;
  font-size: 20em;

  line-height: 5em;
`;
